name: linux

on: [push, pull_request]

jobs:
  centos7:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        LCG: ["LCG_104/x86_64-el9-clang16-opt",
              "LCG_104/x86_64-el9-gcc13-opt"]
        BUILTIN_ZLIB: ["ON", "OFF"]
    steps:
    - uses: actions/checkout@v2
    - uses: cvmfs-contrib/github-action-cvmfs@v2
    - uses: aidasoft/run-lcg-view@v4
      with:
        release-platform: ${{ matrix.LCG }}
        run: |
          echo "::group::Run CMake"
          mkdir build
          cd build
          cmake -DCMAKE_INSTALL_PREFIX=../install \
                -DCMAKE_CXX_STANDARD=17 \
                -DSIO_BUILTIN_ZLIB=${{ matrix.BUILTIN_ZLIB }} \
                -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always -Werror" \
                -G Ninja \
                ..
          echo "::endgroup::" && echo "::group::Build"
          ninja -k0
          echo "::endgroup::" && echo "::group::Test"
          ctest --output-on-failure
          echo "::endgroup::" && echo "::group::Install"
          ninja install
