name: macOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_TYPE: Release

jobs:
  job:
    name: macOS
    runs-on: macos-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
        
      - name: Configure
        run: mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=../bin ..
      - name: Build
        run: cmake --build build
      - name: Install
        run: cmake --install build
